server:
  port: 8080
  servlet:
    context-path: /app
spring:
  profiles:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_data?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update #自动更新，切记不用create，会自动重新创建表的
    show-sql: true
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    host: smtp.qq.com
    username: 1176026424@qq.com
    password: mmybtoihxzrjgeff
    protocol: smtp
    default-encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.Entity
upload-photo-path: /root/apache-tomcat-8.5.39/webapps/static/photo/
upload-music-path: /root/apache-tomcat-8.5.39/webapps/static/music/
upload-video-path: /root/apache-tomcat-8.5.39/webapps/static/video/
upload-technology-path: /root/apache-tomcat-8.5.39/webapps/static/technology/
