server:
  port: 8080
  servlet:
    context-path: /app
spring:
  profiles:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_data?serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update #自动更新，切记不用create，会自动重新创建表的
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.Entity
upload-photo-path: E:/tmp/photo/
upload-music-path: E:/tmp/photo/
